os:
  - linux

services:
  - docker

cache:
  directories:
    - /tmp/cache

env:
  global:
    - GO111MODULE: "on"

language: go

go:
- "1.11.8"

go_import_path: github.com/supergiant/analyze-plugin-sunsetting

install:
- make tools

script:
- source ./scripts/travis_build.sh

#before_cache:
#  - 'sudo rm -Rf /tmp/cache ||:'
#  - mkdir -p /tmp/cache
#  - "docker save -o /tmp/cache/docker.tar $(docker history -q build | tr '\n' ' ' | tr -d '<missing>')"

after_success:
  - echo "Process Done."